apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: galiciachallenge-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      name: galiciachallenge-kubernetes
  template:
    metadata:
      labels:
        name: galiciachallenge-kubernetes
    spec:
      containers:
      - name: galiciachallenge-kubernetes
        image: javierbogado/galiciachallenge-kubernetes
        ports:
        - containerPort: 80
          name: http
