on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    #en este ejemplo no tenemos q hacer un build luego un push por linea de comandos 
    #sino q lo hace el feature docker/build-push-action@v1
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
      #user y pass del docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        #pongo el mismo nombre de repositorio de github al docker registry
        repository: ${{ github.repository }}
        tag_with_ref: true
        #cuando construyo la imagen le appendea el sha
        tag_with_sha: true
        #github.sha usa la version corta del sha
        tags: ${{ github.sha }}
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/my-app galiciachallenge-kubernetes=${{ github.repository }}:${{ github.sha }}
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"rollout status deployment/my-app"'
  ngrok-watcher:
    name: Ngrok watcher
    runs-on: ubuntu-latest
    needs: deploy-to-cluster
    steps:
    - name: Get ngrok URL
      id: getNgrokUrl
      uses: debianmaster/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
      with:
        args: |
          URL=`kubectl -n galiciachallenge-k8s get ngrok -o=custom-columns='DATA:status.url' | tail -n1` 
          echo "::set-output name=url::$URL"
    # - name: Check if URL is valid
    #   uses: ubuntu-latest
    #   run: |
    #     echo "URL is: ${{ steps.getNgrokUrl.outputs.url }}"
      # - name: Watch ngrok
      # uses: steebchen/kubectl@master
      # env:
      #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #   KUBECTL_VERSION: "1.20"
      # run: echo "Hello world"
      # # with:
      # #   args: '"rollout status deployment/my-app"'
